-- 001_schema.sql
ALTER SESSION SET CONTAINER = FREEPDB1;

--------------------------------------------------------------------------------
-- 1) 스키마(유저) 생성: OHAENG
--------------------------------------------------------------------------------
DECLARE
  v_cnt NUMBER := 0;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM dba_users WHERE username = 'OHAENG';
  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE 'CREATE USER OHAENG IDENTIFIED BY ohaeng_pw QUOTA UNLIMITED ON USERS';
    EXECUTE IMMEDIATE 'GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW, CREATE PROCEDURE, CREATE TRIGGER TO OHAENG';
  END IF;
END;
/

--------------------------------------------------------------------------------
-- 2) USERS: 상태/자원/다운/리롤/전투상태
--------------------------------------------------------------------------------
CREATE TABLE OHAENG.O_USERS (
  USER_ID          VARCHAR2(50)  PRIMARY KEY,
  USER_NAME        VARCHAR2(100) NOT NULL,
  EXPERIENCE       NUMBER(18,0)  DEFAULT 0 NOT NULL,
  GOLD             NUMBER(18,0)  DEFAULT 0 NOT NULL,
  CUR_HP           NUMBER(5,0)   DEFAULT 100 NOT NULL,
  MAX_HP           NUMBER(5,0)   DEFAULT 100 NOT NULL,
  CUR_STAMINA      NUMBER(5,0)   DEFAULT 50  NOT NULL,
  MAX_STAMINA      NUMBER(5,0)   DEFAULT 50  NOT NULL,
  LAST_CALC_AT     TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  DOWN_UNTIL       TIMESTAMP     NULL,
  BATTLE_STATE     VARCHAR2(10)  DEFAULT 'NONE' NOT NULL,
  ACTIVE_BATTLE_ID NUMBER(18,0)  NULL,
  ACTIVE_RAID_ID   NUMBER(18,0)  NULL,
  LAST_REROLL_AT   TIMESTAMP     NULL,
  REROLL_DAY       DATE          NULL,
  REROLL_DAY_CNT   NUMBER(2,0)   DEFAULT 0 NOT NULL,
  CREATED_AT       TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL
);

--------------------------------------------------------------------------------
-- 3) WEAPONS: 유저당 무기 1개(UK)
--------------------------------------------------------------------------------
CREATE TABLE OHAENG.O_WEAPONS (
  WEAPON_ID       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  OWNER_ID        VARCHAR2(50)  NOT NULL,
  ELEMENT_TYPE    VARCHAR2(10)  NOT NULL,
  ENHANCE_LEVEL   NUMBER(2,0)   DEFAULT 0 NOT NULL,
  CONSTRAINT FK_WEAPON_OWNER FOREIGN KEY (OWNER_ID)
    REFERENCES OHAENG.O_USERS(USER_ID) ON DELETE CASCADE,
  CONSTRAINT UK_WEAPON_OWNER UNIQUE (OWNER_ID),
  CONSTRAINT CK_ELEMENT_TYPE CHECK (ELEMENT_TYPE IN ('WOOD','FIRE','EARTH','METAL','WATER')),
  CONSTRAINT CK_ENHANCE_LEVEL CHECK (ENHANCE_LEVEL BETWEEN 0 AND 30)
);

CREATE INDEX OHAENG.IDX_WEAPON_OWNER ON OHAENG.O_WEAPONS (OWNER_ID);

--------------------------------------------------------------------------------
-- 4) BATTLES: PvP 결과 + 5라운드 로그(JSON)
--------------------------------------------------------------------------------
CREATE TABLE OHAENG.O_BATTLES (
  BATTLE_ID       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ROOM_ID         VARCHAR2(80)  NOT NULL,
  A_USER_ID       VARCHAR2(50)  NOT NULL,
  B_USER_ID       VARCHAR2(50)  NOT NULL,
  A_SUM           NUMBER(10,0)  DEFAULT 0 NOT NULL,
  B_SUM           NUMBER(10,0)  DEFAULT 0 NOT NULL,
  OUTCOME         VARCHAR2(10)  NOT NULL,
  ROUND_LOG_JSON  CLOB          NOT NULL,
  CREATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX OHAENG.IDX_BATTLES_ROOM ON OHAENG.O_BATTLES (ROOM_ID, CREATED_AT DESC);
CREATE INDEX OHAENG.IDX_BATTLES_A ON OHAENG.O_BATTLES (A_USER_ID, CREATED_AT DESC);
CREATE INDEX OHAENG.IDX_BATTLES_B ON OHAENG.O_BATTLES (B_USER_ID, CREATED_AT DESC);

--------------------------------------------------------------------------------
-- 5) RAIDS: 단톡방 1개 레이드 1개 + 멤버
--------------------------------------------------------------------------------
CREATE TABLE OHAENG.O_RAIDS (
  RAID_ID         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ROOM_ID         VARCHAR2(80)  NOT NULL,
  STATUS          VARCHAR2(12)  NOT NULL,
  BOSS_ID         VARCHAR2(30)  NOT NULL,
  BOSS_NAME       VARCHAR2(50)  NOT NULL,
  BOSS_ELEMENT    VARCHAR2(10)  NOT NULL,
  BOSS_SCORE      NUMBER(10,0)  NOT NULL,
  PARTY_SCORE     NUMBER(10,0)  DEFAULT 0 NOT NULL,
  OUTCOME         VARCHAR2(10)  NULL,
  ROUND_LOG_JSON  CLOB          NULL,
  CREATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX OHAENG.IDX_RAIDS_ROOM ON OHAENG.O_RAIDS (ROOM_ID, CREATED_AT DESC);

CREATE TABLE OHAENG.O_RAID_MEMBERS (
  RAID_ID     NUMBER(18,0) NOT NULL,
  USER_ID     VARCHAR2(50) NOT NULL,
  JOINED_AT   TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_RAID_MEMBERS PRIMARY KEY (RAID_ID, USER_ID),
  CONSTRAINT FK_RAID_MEMBERS_RAID FOREIGN KEY (RAID_ID)
    REFERENCES OHAENG.O_RAIDS(RAID_ID) ON DELETE CASCADE,
  CONSTRAINT FK_RAID_MEMBERS_USER FOREIGN KEY (USER_ID)
    REFERENCES OHAENG.O_USERS(USER_ID) ON DELETE CASCADE
);

CREATE INDEX OHAENG.IDX_RAID_MEMBERS_USER ON OHAENG.O_RAID_MEMBERS (USER_ID);
